name: Pacman Repo Builder
description: Build a custom pacman repository from a collection of PKGBUILD directories
branding:
  icon: package
  color: cyan
inputs:
  command:
    description: Command to run
    required: true
runs:
  using: docker
  image: Dockerfile
